# =============================================================================
# 01_fetch_climate_trace.R — acquire raw source data
# -----------------------------------------------------------------------------
# PURPOSE
#   Fetch the Climate TRACE country package that every downstream script reads,
#   and record enough provenance that a stranger can prove they are working from
#   the same bytes.
#
#   This script is the reproducibility contract for raw data. `data/raw/` is not
#   committed (SKDM_TURKIYE.md §8.6) — reproducibility comes from being able to
#   re-run this, not from a 45 MB blob in git history.
#
# WHY NOT THE REST API
#   `GET /v6/assets/{id}` returns a single year and ignores every year parameter.
#   The bulk country package carries monthly records from 2021 plus the
#   `other1..other10` fields the API omits. See ROADMAP.md, "Closed questions".
#
# OUTPUTS
#   data/raw/climate_trace/TUR_co2.zip          the archive (gitignored)
#   data/raw/climate_trace/extracted/*.csv      sector files (gitignored)
#   data/raw/climate_trace/about_the_data.pdf   upstream documentation
#   data/processed/SOURCES.md                   provenance + attribution chain
#
# RUN
#   Rscript scripts/01_fetch_climate_trace.R
#   Rscript scripts/01_fetch_climate_trace.R --force     # re-download
# =============================================================================

options(encoding = "UTF-8")
options(timeout = 600)                # the package is ~45 MB

source(file.path("scripts", "_sources.R"))

FORCE <- "--force" %in% commandArgs(trailingOnly = TRUE)


# =============================================================================
# 1. CONFIGURATION
# =============================================================================

# CBAM covers CO2 for cement and iron & steel, and CO2 plus PFCs for aluminium.
# Only CO2 is fetched because no `pfc` country package exists. The aluminium gap
# is documented in SOURCES.md below and carried as NA downstream, never filled.
CT_GAS        <- "co2"
CT_COUNTRY    <- "TUR"
CT_SUBSECTORS <- c("iron-and-steel", "cement", "aluminum")

# Upstream documentation. `about_the_data.pdf` is what settles whether a given
# year is a realised observation or a nowcast — an open question in ROADMAP.md
# that cannot be answered from the data alone.
CT_DOCS <- c("about_the_data.pdf", "detailed_data_schema.csv")

DIR_RAW       <- file.path("data", "raw", "climate_trace")
DIR_EXTRACT   <- file.path(DIR_RAW, "extracted")
DIR_PROCESSED <- file.path("data", "processed")

dir.create(DIR_PROCESSED, recursive = TRUE, showWarnings = FALSE)


# =============================================================================
# 2. FETCH
# =============================================================================

message("[1/3] Fetching country package")

pkg <- ct_download_package(gas = CT_GAS, country = CT_COUNTRY,
                           dir = DIR_RAW, force = FORCE)

message("      ", round(pkg$bytes / 1024^2, 1), " MB, sha256 ",
        substr(pkg$sha256, 1, 16), "...")

sector_members <- ct_sector_files(pkg$path, CT_SUBSECTORS)
release_tag    <- ct_release_tag(sector_members)

message("      release: ", release_tag)

extracted <- ct_extract(pkg$path, sector_members, DIR_EXTRACT)


message("[2/3] Fetching upstream documentation")

docs <- CT_DOCS |>
  lapply(function(f) ct_download_doc(f, DIR_RAW)) |>
  Filter(f = Negate(is.null))

message("      ", length(docs), " of ", length(CT_DOCS), " retrieved")


# =============================================================================
# 3. WRITE SOURCES.md — the attribution chain
# =============================================================================
# Climate TRACE is CC BY 4.0. Attribution is a LICENCE CONDITION, not a
# courtesy: redistributing derived data without it is a licence breach. This
# file is what makes the chain auditable, and it is surfaced in the app's
# "Veri Kaynakları" tab.

message("[3/3] Writing SOURCES.md")

fmt_row <- function(label, value) paste0("| ", label, " | ", value, " |")

lines <- c(
  "# Data sources",
  "",
  paste0("Generated by `scripts/01_fetch_climate_trace.R` on ",
         format(Sys.Date(), "%Y-%m-%d"), "."),
  "This file is generated. Do not edit by hand — re-run the script.",
  "",
  "---",
  "",
  "## Climate TRACE — facility-level emissions",
  "",
  "> Climate TRACE (climatetrace.org). Licensed under Creative Commons",
  "> Attribution 4.0 International (CC BY 4.0).",
  "",
  "| field | value |",
  "|---|---|",
  fmt_row("Package URL", paste0("`", pkg$url, "`")),
  fmt_row("Release tag", paste0("**", release_tag, "**")),
  fmt_row("Gas", paste0("`", pkg$gas, "`")),
  fmt_row("Country", pkg$country),
  fmt_row("Retrieved", pkg$retrieved_at),
  fmt_row("Size", paste0(round(pkg$bytes / 1024^2, 2), " MB")),
  fmt_row("SHA-256", paste0("`", pkg$sha256, "`")),
  fmt_row("Licence", pkg$licence),
  "",
  "### Files used",
  "",
  "| subsector | archive member |",
  "|---|---|",
  paste0("| ", names(sector_members), " | `", unname(sector_members), "` |"),
  "",
  "### A note on the release tag",
  "",
  "The download URL uses the `latest` alias, which advances silently when a new",
  "release lands. The tag above is extracted from the archive's own filenames",
  "and is the version that must be cited. It is **not** the same as the REST",
  "API's `v6`: the API is a different artefact and may serve a different",
  "release. Re-running this script with `--force` after an upstream update will",
  "produce a different SHA-256, which is the intended signal that results need",
  "regenerating.",
  ""
)

if (length(docs) > 0) {
  lines <- c(lines,
    "### Upstream documentation retrieved",
    "",
    "| file | sha256 |",
    "|---|---|",
    vapply(docs, function(d)
      paste0("| `", basename(d$path), "` | `", substr(d$sha256, 1, 32), "...` |"),
      character(1)),
    ""
  )
}

lines <- c(lines,
  "---",
  "",
  "## Known source gaps",
  "",
  "These are properties of the upstream data, not of this pipeline. They are",
  "recorded here so that a reader can see what could not be obtained rather",
  "than wondering what was quietly omitted.",
  "",
  "- **Aluminium PFCs.** CBAM covers CO2 *and* perfluorocarbons for aluminium.",
  "  Climate TRACE publishes no `pfc` country package, so aluminium exposure",
  "  computed here is an underestimate. The gap is carried as `NA` and shown in",
  "  the UI; it is never filled with a substitute value (SKDM_TURKIYE.md §8.1).",
  "- **Fertilisers.** No fertiliser-*production* subsector exists. The similarly",
  "  named `synthetic-fertilizer-application` covers N2O from fertiliser applied",
  "  to agricultural soils — a different emission source, and not what CBAM",
  "  regulates. Fertilisers are therefore out of scope; see ROADMAP.md.",
  "- **Verified facility reports.** Turkish installations report verified GHG",
  "  figures to the authorities, but these are not publicly released. Every",
  "  emissions figure in this project is a modelled estimate and is marked as",
  "  such in the UI (§8.3).",
  "",
  "---",
  "",
  "## Licensing of this repository's outputs",
  "",
  "| artefact | licence |",
  "|---|---|",
  "| Source code | MIT |",
  "| Documentation and derived data | CC BY 4.0 |",
  "| Upstream data | retains its original licence (above) |",
  "",
  "Derived data published under CC BY 4.0 remains subject to the attribution",
  "requirement of its upstream source. The chain must be carried forward, not",
  "replaced."
)

writeLines(lines, file.path(DIR_PROCESSED, "SOURCES.md"), useBytes = TRUE)


# =============================================================================
# 4. CONSOLE REPORT
# =============================================================================

cat("\n", strrep("=", 72), "\n", sep = "")
cat("FETCH COMPLETE\n")
cat(strrep("=", 72), "\n\n", sep = "")
cat("Package : ", pkg$path, "\n", sep = "")
cat("Release : ", release_tag, "\n", sep = "")
cat("SHA-256 : ", pkg$sha256, "\n", sep = "")
cat("Retrieved: ", pkg$retrieved_at, "\n\n", sep = "")
cat("Extracted ", length(extracted), " sector files to ", DIR_EXTRACT, "\n", sep = "")
for (nm in names(extracted)) cat("  ", nm, "\n", sep = "")
cat("\nWritten: ", file.path(DIR_PROCESSED, "SOURCES.md"), "\n", sep = "")
